export type HelpSection = {
  title: string;
  summary: string;
  steps: string[];
  permission?: string | string[];
};

export type HelpFaq = {
  question: string;
  answer: string;
  permission?: string | string[];
};

export const workspaceHelpSections: HelpSection[] = [
  { title: "Your dashboard", summary: "Your overview is personalized from your assigned role and permissions.", steps: ["Use the left navigation to open only the modules assigned to your account.", "Review notices and deadlines before starting work.", "Use your profile menu to manage personal details or switch to the customer portal without signing out."] },
  { title: "People and employee access", summary: "HR records and sign-in accounts are related, but are separate records.", steps: ["Open People → Employees to find or maintain an employee record.", "Authorized administrators can provision access by invitation or a temporary password.", "Never share temporary passwords; employees set their own password after activation. Disabling access preserves employment and work history."], permission: ["hr.read", "hr.manage", "users.manage"] },
  { title: "Leave and payslips", summary: "Submit leave for review and view salary slips published for your account.", steps: ["Submit dates and a leave type; provide supporting details only when relevant.", "Your immediate manager reviews the request and HR finalizes it according to company policy.", "Published payslips are read-only. Contact HR/Payroll if an issued record needs correction."], permission: ["leave.request", "leave.approve", "payroll.read_self", "payroll.manage"] },
  { title: "Projects and tasks", summary: "Track assigned delivery work and its due dates.", steps: ["Open My work for your assignments or Projects/Tasks for broader work you are authorized to see.", "Update status and progress promptly; use comments for decisions and blockers.", "Keep project, tender, and task records linked instead of creating duplicates."], permission: ["project.manage", "task.create", "task.assign", "task.edit"] },
  { title: "CRM, RFQs, quotations and contracts", summary: "Manage the customer-to-delivery record chain.", steps: ["Confirm the customer/contact before creating a lead or RFQ.", "Create quotation revisions as new versions so previously sent terms remain traceable.", "Only authorized staff should approve/send commercial documents or advance an accepted quotation to contract."], permission: ["crm.read", "crm.write", "rfq.read", "rfq.write", "quotation.create", "quotation.edit", "quotation.approve", "contract.create"] },
  { title: "Tender operations", summary: "Track deadlines, requirements, securities, correspondence, and final submission evidence.", steps: ["Keep the tender reference, deadline, requirements and assigned tasks current.", "Record CPO/bank-guarantee details and expiry evidence against the correct tender.", "Use the linked letter workflow for correspondence; a submitted final snapshot must not be edited."], permission: ["tender.read", "tender.create", "tender.view_all", "tender.manage_guarantees"] },
  { title: "Finance", summary: "Use finance records for operational control and approvals.", steps: ["Link requests and transactions to the right customer, project, budget and supporting evidence.", "Review dates, currency, tax evidence and attachments before submission.", "This management module does not replace statutory accounting or tax advice."], permission: ["finance.read", "finance.create", "finance.approve", "expense.request"] },
  { title: "Letters and documents", summary: "Create controlled company correspondence and retain source files securely.", steps: ["Use an approved template when available and verify recipient/signatory details.", "Drafts can be edited; publishing/submission require the appropriate permission.", "Submitted letters are final. To correct one, duplicate it as a new draft and retain the source relationship."], permission: ["files.manage", "letters.read", "letters.create", "letters.publish", "letters.submit"] },
  { title: "Content and system administration", summary: "Control the website and organization configuration only within your assigned scope.", steps: ["Preview public content before publishing; check links and media on desktop and mobile.", "Manage accounts through the admin access tools; assign only the least permissions needed.", "Configuration changes can affect both staff and customer views; record and review them carefully."], permission: ["cms.read", "cms.write", "cms.publish", "settings.manage", "users.manage"] },
];

export const customerHelpSections: HelpSection[] = [
  { title: "Your customer dashboard", summary: "The portal shows records linked to your customer account only.", steps: ["Use the portal menu to open your dashboard, company information, services, and contact pages.", "Your sign-in session stays active while you browse the customer portal.", "If you are a Betanor employee previewing the portal, use the return-to-workspace link to go back."] },
  { title: "Request a quotation", summary: "Send Betanor a request about a service or product.", steps: ["Choose the relevant service or product and start a quotation request.", "Describe the requirement, quantities or scope, and a useful contact method.", "You can follow linked requests and quotations from the portal after the team processes them."] },
  { title: "Track requests and commercial records", summary: "View the RFQs, quotations, contracts and project records associated with your account.", steps: ["Open your portal dashboard to review available records and current statuses.", "If an item is missing, contact Betanor so staff can check the customer-account link.", "Only information associated with your customer access is displayed."] },
  { title: "Messages and support", summary: "Use the floating chat control or Betanor contact channels to ask for assistance.", steps: ["Open the chat icon at the lower-right of the page to start or continue a conversation.", "Do not send passwords, payment-card details, or other highly sensitive information in chat.", "For an urgent or formal request, use the Contact page and include your organization and reference number."] },
  { title: "Profile and sign-in", summary: "Keep your account contact information current and protect your sign-in.", steps: ["Use the profile button to review available account settings.", "Never share your password or one-time sign-in link.", "If you cannot access the right organization's records, contact Betanor to review the portal access assignment."] },
];

export const workspaceFaqs: HelpFaq[] = [
  { question: "Why can’t I see a module?", answer: "Workspace navigation and dashboard cards follow your active role and assigned permissions. Ask your manager or a system administrator to review your access. A hidden link is not a substitute for authorization, so do not use another person’s account." },
  { question: "How do I switch to the customer portal without signing out?", answer: "Use the profile menu in the upper-right and choose Customer portal. Return with Staff workspace. Your authenticated session stays active until you choose Sign out." },
  { question: "How do I get a user account or reset my password?", answer: "An authorized administrator provisions staff accounts and can resend an invitation or password-reset email. Use Forgot password on the sign-in page for a self-service reset. Never send a password through chat or email." },
  { question: "Can I change a published payroll run?", answer: "No. Payroll changes are made while a cycle is still a draft. Review the employee rows and imported workbook before submitting, approving, and publishing. If a published pay record is wrong, contact HR/Payroll for the approved correction process.", permission: ["payroll.manage", "payroll.read_self"] },
  { question: "How do I import payroll from Excel?", answer: "Download the Excel workbook for the draft cycle, update the Gross Pay and Deductions columns, keep each Employee ID unchanged, and upload the saved .xlsx file back to the same draft cycle. Net Pay is recalculated by the system. Formulas in imported pay cells are not accepted; use final numeric values.", permission: "payroll.manage" },
  { question: "How do leave requests get approved?", answer: "Submit the dates and leave type in Leave. Your immediate manager reviews the request first, followed by HR where required. The request remains pending until the workflow records its decision.", permission: ["leave.request", "leave.approve"] },
  { question: "How do I correct an official letter after submission?", answer: "A submitted letter is final. Open it and choose Duplicate as New Draft, then make the correction on the new letter. The new reference and source relationship preserve the history.", permission: ["letters.read", "letters.create", "letters.view_all", "letters.view_department"] },
  { question: "Where can I report an IT support issue?", answer: "Open the Support module to create or update a ticket, add screenshots or files, and follow technician messages. The support dashboard only shows tickets available to your assigned role.", permission: ["support.read", "support.create", "support.view_all"] },
  { question: "What should I do if a record or notification looks wrong?", answer: "Do not create a duplicate record to work around it. Capture the reference number, page, and time, then contact your manager or administrator. They can review the record and its audit history." },
];

export const customerFaqs: HelpFaq[] = [
  { question: "How do I access my customer account?", answer: "Use Sign in/Sign up on the Betanor website. After sign-in, the portal displays records linked to your customer account. If the organization or account shown is wrong, contact Betanor so the access link can be checked." },
  { question: "How do I request a quotation?", answer: "Open Services or Products, choose Request a quotation, and describe the need, scope, quantity, and preferred contact details. The request appears in your portal after it is linked to your account." },
  { question: "How do I contact support?", answer: "Open IT Support to create a ticket, or use the chat icon at the lower-right of the page to message Betanor. Attach a screenshot or file when it helps explain the issue. Do not send passwords or payment-card details." },
  { question: "Can I browse the public site without signing out?", answer: "Yes. You can move between Home, About, Services, Contact, and Partner pages while signed in. Your session remains active until you choose Sign out." },
  { question: "Where do I see my request and contract status?", answer: "Return to the customer dashboard. It shows the RFQs, quotations, contracts, projects, and invoices associated with your customer access. Contact Betanor if a record is missing." },
  { question: "How do I reset my password?", answer: "Choose Forgot password on the sign-in page and follow the secure email link. Use the newest reset email and do not forward the link to anyone." },
];
