import { redirect } from "next/navigation";
import Link from "next/link";
import { Card } from "@/components/ui/card";
import { SupportRequestForm } from "@/components/portal/support-request-form";
import { createClient } from "@/lib/supabase/server";

/* eslint-disable @typescript-eslint/no-explicit-any -- support tables arrive in the paired database migration. */

export default async function CustomerSupportPage(){
 const supabase=await createClient(); const {data:claims}=await supabase.auth.getClaims(); const userId=typeof claims?.claims.sub==="string"?claims.claims.sub:null; if(!userId) redirect("/login?next=/portal/support");
 const {data:link}=await supabase.from("customer_portal_access").select("customer_id,customers(id,name,workspace_id)").eq("profile_id",userId).eq("is_active",true).limit(1).maybeSingle(); if(!link?.customer_id) redirect("/customer/onboard");
 const customer=Array.isArray(link.customers)?link.customers[0]:link.customers; const db=supabase as any; const {data:tickets}=await db.from("support_tickets").select("id,ticket_number,title,status,priority,created_at,updated_at").eq("customer_id",link.customer_id).order("created_at",{ascending:false}).limit(30);
 return <main className="mx-auto max-w-6xl px-5 py-8 sm:px-6 lg:px-8 lg:py-10"><p className="text-sm font-semibold tracking-widest text-[var(--betanor-blue)] uppercase">Customer support</p><h1 className="mt-2 text-3xl font-semibold text-[var(--betanor-navy)]">How can we help?</h1><p className="mt-2 text-sm text-[var(--betanor-muted)]">Support for {customer?.name}. Submit a request or continue the live chat with Betanor.</p><div className="mt-6 grid gap-5 lg:grid-cols-[1fr_1fr]"><Card className="p-5"><h2 className="mb-4 font-semibold text-[var(--betanor-navy)]">Create support request</h2><SupportRequestForm customerId={link.customer_id} workspaceId={customer?.workspace_id??""}/></Card><Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-[var(--betanor-navy)]">My support tickets</h2><span className="text-xs text-[var(--betanor-muted)]">{tickets?.length??0} recent</span></div>{tickets?.length?<div className="mt-4 divide-y">{tickets.map((ticket:any)=><div key={ticket.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-xs font-semibold text-[var(--betanor-blue)]">{ticket.ticket_number}</p><Link href={`/portal/support/tickets/${ticket.id}`} className="mt-1 block text-sm font-medium text-[var(--betanor-navy)] hover:text-[var(--betanor-blue)]">{ticket.title} →</Link><p className="mt-1 text-xs text-[var(--betanor-muted)]">{new Date(ticket.created_at).toLocaleDateString("en-ET")}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{ticket.status}</span></div>)}</div>:<p className="mt-5 text-sm text-[var(--betanor-muted)]">No requests yet. Our team is ready when you need us.</p>}</Card></div><Card className="mt-5 p-5"><h2 className="font-semibold text-[var(--betanor-navy)]">RTSL support coverage</h2><p className="mt-2 text-sm leading-6 text-[var(--betanor-muted)]">Remote and onsite support across Windows and Mac, workstation deployment, networking, video conferencing, telephony, device lifecycle, configuration, security, software, remote access and staff joiner/leaver support. Planned onsite window: Thursday, 9:00 AM–12:00 PM.</p></Card></main>;
}
