import { redirect } from "next/navigation";

import { DepartmentPositionManager } from "@/components/admin/department-position-manager";
import { Badge } from "@/components/ui/badge";
import { createClient } from "@/lib/supabase/server";
import { resolveWorkspace } from "@/lib/workspace-context";

export const dynamic = "force-dynamic";

export default async function DepartmentsPage() {
  const access = await resolveWorkspace(await createClient());
  if (!access.permissions.has("hr.manage") && !access.permissions.has("users.manage") && !access.permissions.has("settings.manage")) redirect("/workspace");
  return <main className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold tracking-[0.14em] text-[var(--betanor-blue)] uppercase">Administration / people</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-[var(--betanor-navy)]">Departments & positions</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--betanor-muted)]">Maintain the organization tree and its departmental positions. New codes are generated by Supabase and remain stable across employee, recruitment, and payroll records.</p></div><Badge tone="info">Role protected</Badge></div><DepartmentPositionManager /></main>;
}
