import { redirect } from "next/navigation";

import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { createClient } from "@/lib/supabase/server";
import { resolveWorkspace } from "@/lib/workspace-context";

export const dynamic = "force-dynamic";

export default async function KpisPage() {
  const supabase = await createClient();
  const access = await resolveWorkspace(supabase);
  if (!access.permissions.has("kpi.read_self") && !access.permissions.has("kpi.read_team") && !access.permissions.has("kpi.configure") && !access.permissions.has("kpi.review")) redirect("/workspace");
  const { data: kpis, error } = access.workspaceId ? await supabase.from("kpis").select("id,name,unit,target_value,current_value,status,period_end,departments(name)").eq("workspace_id", access.workspaceId).order("period_end", { ascending: true, nullsFirst: false }).limit(30) : { data: [], error: null };
  return <main className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-semibold tracking-[0.14em] text-[var(--betanor-blue)] uppercase">Strategy & performance</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-[var(--betanor-navy)]">KPI review</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--betanor-muted)]">See the measures assigned to your workspace and the progress against each approved target.</p></div><Badge tone="info">Permission scoped</Badge></div>{error ? <Card className="mt-8 p-6"><p className="font-semibold text-[var(--betanor-navy)]">KPI data is not available for this role.</p><p className="mt-2 text-sm text-[var(--betanor-muted)]">Ask management to assign team KPI visibility.</p></Card> : kpis?.length ? <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{kpis.map((kpi) => { const target = Number(kpi.target_value ?? 0); const current = Number(kpi.current_value ?? 0); const progress = target > 0 ? Math.min(100, Math.round((current / target) * 100)) : 0; const department = Array.isArray(kpi.departments) ? kpi.departments[0] : kpi.departments; return <Card key={kpi.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[var(--betanor-navy)]">{kpi.name}</p><p className="mt-1 text-xs text-[var(--betanor-muted)]">{department?.name || "Workspace"}{kpi.period_end ? ` · due ${kpi.period_end}` : ""}</p></div><Badge tone={kpi.status === "active" ? "success" : "draft"}>{kpi.status}</Badge></div><div className="mt-5 flex items-end justify-between"><p className="text-2xl font-semibold text-[var(--betanor-navy)]">{current.toLocaleString()}</p><p className="text-xs text-[var(--betanor-muted)]">of {target.toLocaleString()} {kpi.unit}</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[var(--betanor-blue)]" style={{ width: `${progress}%` }} /></div><p className="mt-2 text-right text-xs font-semibold text-[var(--betanor-blue)]">{progress}%</p></Card>; })}</div> : <Card className="mt-8 p-8"><p className="font-semibold text-[var(--betanor-navy)]">No KPIs have been configured yet.</p><p className="mt-2 text-sm leading-6 text-[var(--betanor-muted)]">Management can connect annual goals, department goals, initiatives, projects, and measurable results here.</p></Card>}</main>;
}
