"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { createClient } from "@/lib/supabase/client";

/* eslint-disable @typescript-eslint/no-explicit-any -- support RPC/types are migration-backed. */
const nextStatus:Record<string,string[]>={New:["Acknowledged","Assigned","Cancelled"],Acknowledged:["Assigned","In Progress","Waiting for Customer","Waiting for Internal Team","Cancelled"],Assigned:["In Progress","Waiting for Customer","Waiting for Internal Team","Scheduled Remote Session","Scheduled On-Site Visit","Cancelled"],"In Progress":["Waiting for Customer","Waiting for Internal Team","Scheduled Remote Session","Scheduled On-Site Visit","Resolved"],"Waiting for Customer":["In Progress","Scheduled Remote Session","Scheduled On-Site Visit","Cancelled"],"Waiting for Internal Team":["In Progress","Cancelled"],"Scheduled Remote Session":["In Progress","Waiting for Customer","Resolved","Cancelled"],"Scheduled On-Site Visit":["In Progress","Waiting for Customer","Resolved","Cancelled"],Resolved:["Closed","Reopened"],Reopened:["In Progress","Cancelled"]};
export function SupportTicketActions({ticketId,currentStatus,canRespond,technicians}:{ticketId:string;currentStatus:string;canRespond:boolean;technicians:{id:string;label:string}[]}) {
 const options=nextStatus[currentStatus]??[]; const [status,setStatus]=useState(options[0]??""); const [employee,setEmployee]=useState(technicians[0]?.id??""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const router=useRouter(); const db=createClient() as any;
 async function call(name:string,args:Record<string,unknown>){setBusy(true);setMessage("");const {error}=await db.rpc(name,args);setBusy(false);if(error){setMessage("That update could not be saved. Check your access and try again.");return;}router.refresh();}
 return <div className="mt-5 space-y-3 border-t pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--betanor-muted)]">Ticket actions</p>{technicians.length?<div className="flex gap-2"><select aria-label="Assign technician" value={employee} onChange={e=>setEmployee(e.target.value)} className="min-w-0 flex-1 rounded-lg border px-2 text-sm">{technicians.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select><Button size="sm" disabled={busy||!employee} onClick={()=>void call("assign_support_ticket",{p_ticket:ticketId,p_employee:employee})}>Assign</Button></div>:null}{canRespond&&options.length?<div className="flex gap-2"><select aria-label="Update ticket status" value={status} onChange={e=>setStatus(e.target.value)} className="min-w-0 flex-1 rounded-lg border px-2 text-sm">{options.map(x=><option key={x}>{x}</option>)}</select><Button size="sm" disabled={busy||!status} onClick={()=>void call("update_support_ticket_status",{p_ticket:ticketId,p_status:status,p_note:null})}>Update</Button></div>:null}{message?<p role="alert" className="text-xs text-red-700">{message}</p>:null}</div>;
}
