"use client";
import { useCallback, useEffect, useState } from "react";
import { ChatComposer } from "@/components/chat/chat-composer";
import { createClient } from "@/lib/supabase/client";

type Message={id:string;body:string;sender_kind:string;is_internal:boolean;attachment_name:string|null;read_at:string|null;created_at:string};
export function SupportConversation({conversationId,senderKind}:{conversationId:string;senderKind:"agent"|"customer"}) {
 const [messages,setMessages]=useState<Message[]>([]);
 const load=useCallback(async()=>{const supabase=createClient();const {data}=await supabase.from("chat_messages").select("id,body,sender_kind,is_internal,attachment_name,read_at,created_at").eq("conversation_id",conversationId).eq("is_internal",false).order("created_at").limit(100);setMessages((data??[]) as Message[]);void supabase.rpc("mark_chat_messages_read",{conversation_id_input:conversationId});},[conversationId]);
 useEffect(()=>{const supabase=createClient();const initial=window.setTimeout(()=>void load(),0);const channel=supabase.channel(`betanor-support-conversation-${conversationId}`).on("postgres_changes",{event:"*",schema:"public",table:"chat_messages",filter:`conversation_id=eq.${conversationId}`},()=>void load()).subscribe();return()=>{window.clearTimeout(initial);void supabase.removeChannel(channel);};},[conversationId,load]);
 return <><div aria-live="polite" className="mt-4 max-h-80 space-y-2 overflow-y-auto rounded-lg bg-slate-50 p-3">{messages.length?messages.map(message=><div key={message.id} className={`max-w-[90%] rounded-xl px-3 py-2 text-sm ${message.sender_kind===senderKind?"ml-auto bg-blue-100 text-[var(--betanor-navy)]":"bg-white text-[var(--betanor-text)]"}`}><p className="whitespace-pre-wrap">{message.body}</p>{message.attachment_name?<a className="mt-2 block text-xs font-semibold text-[var(--betanor-blue)] underline" href={`/api/chat/attachments/${message.id}`} target="_blank" rel="noreferrer">📎 {message.attachment_name}</a>:null}<p className="mt-1 text-right text-[10px] text-slate-500">{message.sender_kind===senderKind&&message.read_at?"Seen · ":""}{new Date(message.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</p></div>):<p className="p-3 text-sm text-[var(--betanor-muted)]">No messages yet. Send a message to start the support conversation.</p>}</div><p className="mt-1 text-right text-[10px] text-[var(--betanor-muted)]">Messages update live</p><ChatComposer conversationId={conversationId} senderKind={senderKind} placeholder={senderKind==="agent"?"Reply to the customer…":"Write to your Betanor technician…"} onSent={()=>void load()}/></>;
}
