"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { createClient } from "@/lib/supabase/client";

/* eslint-disable @typescript-eslint/no-explicit-any -- migration-backed support ticket type. */
export function SupportCreateTicketForm({workspaceId,customers}:{workspaceId:string;customers:{id:string;name:string}[]}){const [saving,setSaving]=useState(false);const [error,setError]=useState("");const router=useRouter();async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const data=new FormData(formElement);setSaving(true);setError("");const supabase=createClient() as any;const {data:{user}}=await supabase.auth.getUser();if(!user){setError("Please sign in again.");setSaving(false);return;}const {error:insertError}=await supabase.from("support_tickets").insert({workspace_id:workspaceId,customer_id:String(data.get("customerId")),requester_profile_id:user.id,title:String(data.get("title")),description:String(data.get("description")),category:String(data.get("category")),priority:String(data.get("priority")),source:"staff",ticket_number:""});setSaving(false);if(insertError){setError("Ticket could not be created. Check your access and required fields.");return;}router.push("/workspace/support/tickets");router.refresh();}
return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Customer<select name="customerId" required className="min-h-11 rounded-lg border px-3 text-sm">{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Priority<select name="priority" className="min-h-11 rounded-lg border px-3 text-sm"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className="grid gap-1 text-sm font-medium sm:col-span-2">Issue title<input name="title" required minLength={4} maxLength={180} className="min-h-11 rounded-lg border px-3 text-sm"/></label><label className="grid gap-1 text-sm font-medium">Category<select name="category" className="min-h-11 rounded-lg border px-3 text-sm">{["General","Workstation deployment","Windows / Mac","Networking","Video conferencing","Telephony","Hardware / software","Security configuration","Onboarding/offboarding"].map(c=><option key={c}>{c}</option>)}</select></label><label className="grid gap-1 text-sm font-medium sm:col-span-2">Description<textarea name="description" required minLength={10} rows={5} className="rounded-lg border px-3 py-2 text-sm"/></label>{error?<p role="alert" className="text-sm text-red-700 sm:col-span-2">{error}</p>:null}<div><Button disabled={saving}>{saving?"Creating…":"Create ticket"}</Button></div></form>;}
