import Link from "next/link";
import { notFound } from "next/navigation";
import { Card } from "@/components/ui/card";
import { SupportConversation } from "@/components/support/support-conversation";
import { SupportTicketConfirm } from "@/components/portal/support-ticket-confirm";
import { createClient } from "@/lib/supabase/server";

/* eslint-disable @typescript-eslint/no-explicit-any -- support tables are added by paired migration. */
export default async function CustomerTicketPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const supabase=await createClient();const {data:ticket}=await (supabase as any).from("support_tickets").select("id,ticket_number,title,description,status,priority,created_at").eq("id",id).maybeSingle();if(!ticket)notFound();const {data:conversation}=await (supabase as any).from("chat_conversations").select("id").eq("support_ticket_id",id).maybeSingle();return <main className="mx-auto max-w-4xl px-5 py-8 sm:px-6 lg:px-8"><Link href="/portal/support" className="text-sm font-semibold text-[var(--betanor-blue)]">← My support</Link><p className="mt-5 text-xs font-bold tracking-widest text-[var(--betanor-blue)]">{ticket.ticket_number}</p><h1 className="mt-2 text-3xl font-semibold text-[var(--betanor-navy)]">{ticket.title}</h1><p className="mt-2 text-sm text-[var(--betanor-muted)]">{ticket.status} · {ticket.priority} priority · Opened {new Date(ticket.created_at).toLocaleDateString("en-ET")}</p><Card className="mt-5 p-5"><h2 className="font-semibold">Your request</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{ticket.description}</p>{ticket.status==="Resolved"?<SupportTicketConfirm ticketId={ticket.id}/>:null}</Card>{conversation?.id?<Card className="mt-5 p-5"><h2 className="font-semibold text-[var(--betanor-navy)]">Message your technician</h2><p className="mt-1 text-xs text-[var(--betanor-muted)]">Replies appear here in real time. You can attach a screenshot or document.</p><SupportConversation conversationId={conversation.id} senderKind="customer"/></Card>:null}</main>;}
