import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import { PublicHeader } from "@/components/navigation/public-header";
import { SiteFooter } from "@/components/navigation/site-footer";
import { PageHero } from "@/components/public/page-hero";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/server";
async function startChat(data: FormData){"use server";const supabase=await createClient();const {data:result,error}=await supabase.rpc("start_guest_chat",{name_input:String(data.get("name")??"").trim(),email_input:String(data.get("email")??"").trim(),topic_input:String(data.get("topic")??"").trim(),message_input:String(data.get("message")??"").trim()});if(error||!result?.[0]?.reference||!result?.[0]?.token)redirect("/chat?error=1");const cookieStore=await cookies();cookieStore.set("betanor_chat_token",result[0].token,{httpOnly:true,secure:true,sameSite:"lax",path:"/chat",maxAge:60*60*24*30});redirect(`/chat?reference=${encodeURIComponent(result[0].reference)}`)}
async function sendMessage(data: FormData){"use server";const token=(await cookies()).get("betanor_chat_token")?.value??"";const body=String(data.get("body")??"").trim();if(!token||!body)return;const supabase=await createClient();await supabase.rpc("send_guest_chat_message",{token_input:token,message_input:body});redirect(`/chat?reference=${encodeURIComponent(String(data.get("reference")??""))}`)}
export default async function ChatPage({searchParams}:{searchParams:Promise<{reference?:string;error?:string}>}){const q=await searchParams;const token=(await cookies()).get("betanor_chat_token")?.value??"";const supabase=await createClient();const {data:messages}=q.reference&&token?await supabase.rpc("get_guest_chat",{token_input:token}):{data:null};return <><PublicHeader/><main><PageHero eyebrow="Talk to Betanor" title="Start a conversation with our technology team.">For solution design, products, implementation, support, or training, share the context and the team will route it to the right specialist.</PageHero><section className="mx-auto max-w-3xl px-6 py-14 lg:px-8">{q.reference?<div className="rounded-2xl border border-[var(--betanor-border)] bg-white p-7"><div className="rounded-xl bg-emerald-50 p-5 text-emerald-950"><h2 className="text-xl font-semibold">Your conversation is open.</h2><p className="mt-2 text-sm">Reference: <strong>{q.reference}</strong>. Keep this browser session open to continue the conversation.</p></div><div className="mt-6 space-y-3">{messages?.map((m:{message_id:string;sender_kind:string;body:string})=><p key={m.message_id} className="rounded-lg bg-slate-50 p-3 text-sm"><strong>{m.sender_kind === "guest" ? "You" : "Betanor"}:</strong> {m.body}</p>)}</div><form action={sendMessage} className="mt-6"><input type="hidden" name="reference" value={q.reference}/><textarea required minLength={2} name="body" rows={3} className="w-full rounded-lg border border-[var(--betanor-border)] px-3 py-2 text-sm" placeholder="Send a follow-up message"/><Button type="submit" className="mt-3">Send message</Button></form></div>:<form action={startChat} className="grid gap-5 rounded-2xl border border-[var(--betanor-border)] bg-white p-7 sm:grid-cols-2"><label className="text-sm font-semibold text-[var(--betanor-navy)]">Name<Input required name="name" className="mt-2"/></label><label className="text-sm font-semibold text-[var(--betanor-navy)]">Email<Input name="email" type="email" className="mt-2"/></label><label className="text-sm font-semibold text-[var(--betanor-navy)] sm:col-span-2">Topic<Input name="topic" className="mt-2" placeholder="For example: office network upgrade"/></label><label className="text-sm font-semibold text-[var(--betanor-navy)] sm:col-span-2">How can we help?<textarea required minLength={2} name="message" rows={6} className="mt-2 w-full rounded-lg border border-[var(--betanor-border)] px-3 py-2 text-sm"/></label>{q.error?<p className="text-sm text-[var(--betanor-danger)] sm:col-span-2">Please complete your name and message.</p>:null}<div className="sm:col-span-2"><Button type="submit">Start conversation</Button></div></form>}</section></main><SiteFooter/></>}
