"use client";

import { useState } from "react";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { FieldLabel, Input } from "@/components/ui/input";
import { Modal } from "@/components/ui/modal";

type Option = { id: string; label: string };
export type EmployeeAdminRecord = {
  id: string;
  profile_id: string | null;
  first_name: string;
  last_name: string;
  work_email: string | null;
  work_phone: string | null;
  hire_date: string | null;
  probation_end_date: string | null;
  department_id: string | null;
  position_id: string | null;
  manager_id: string | null;
  employment_type: string | null;
  employment_status: string | null;
  contract_title: string;
  salary_amount: number | null;
};

type Props = { departments: Option[]; positions: Option[]; profiles: Option[]; managers: Option[]; employees: EmployeeAdminRecord[]; canManage: boolean };

const emptyForm = { firstName: "", lastName: "", profileId: "", workEmail: "", workPhone: "", hireDate: "", probationEndDate: "", departmentId: "", positionId: "", managerId: "", employmentType: "full_time", salary: "", contractTitle: "Employment contract", employmentStatus: "active" };

export function EmployeeManagementPanel({ departments, positions, profiles, managers, employees, canManage }: Props) {
  const [open, setOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState(emptyForm);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  function field(name: keyof typeof emptyForm, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  function startCreate() { setEditingId(null); setForm({ ...emptyForm }); setError(null); setNotice(null); setOpen(true); }
  function startEdit(employee: EmployeeAdminRecord) {
    setEditingId(employee.id);
    setForm({ firstName: employee.first_name, lastName: employee.last_name, profileId: employee.profile_id ?? "", workEmail: employee.work_email ?? "", workPhone: employee.work_phone ?? "", hireDate: employee.hire_date ?? "", probationEndDate: employee.probation_end_date ?? "", departmentId: employee.department_id ?? "", positionId: employee.position_id ?? "", managerId: employee.manager_id ?? "", employmentType: employee.employment_type ?? "full_time", salary: employee.salary_amount ? String(employee.salary_amount) : "", contractTitle: employee.contract_title || "Employment contract", employmentStatus: employee.employment_status ?? "active" });
    setError(null); setNotice(null); setOpen(true);
  }
  function close() { if (!saving) setOpen(false); }

  async function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setError(null); setNotice(null);
    try {
      const response = await fetch("/api/admin/employees", { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, id: editingId, salary: form.salary ? Number(form.salary) : 0 }) });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload.error || "Could not save employee.");
      setNotice(editingId ? "Employee updated." : `Employee created with ID ${payload.employee?.employee_number || "generated by Supabase"}.`);
      setOpen(false); window.location.reload();
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save employee."); }
    finally { setSaving(false); }
  }

  async function remove(employee: EmployeeAdminRecord) {
    if (!window.confirm(`Delete ${employee.first_name} ${employee.last_name}? Records with payroll, leave, or task history are archived safely.`)) return;
    setSaving(true); setError(null);
    try {
      const response = await fetch("/api/admin/employees", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: employee.id }) });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload.error || "Could not delete employee.");
      setNotice(payload.archived ? "Employee history exists; the profile was archived." : "Employee deleted."); window.location.reload();
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not delete employee."); }
    finally { setSaving(false); }
  }

  if (!canManage) return <Card className="mt-8 p-6 text-sm text-[var(--betanor-muted)]">Employee administration access is required for create, update, and delete actions.</Card>;
  return <>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-[var(--betanor-navy)]">Employee administration</h2><p className="mt-1 text-sm text-[var(--betanor-muted)]">Create, update, archive, or remove employee records without leaving the directory.</p></div><Button onClick={startCreate}>New employee</Button></div>
    {notice ? <p role="status" className="mt-4 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-900">{notice}</p> : null}
    {error ? <p role="alert" className="mt-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-800">{error}</p> : null}
    {open ? <Modal title={editingId ? "Update employee" : "Create employee"} onClose={close} className="max-w-4xl"><form onSubmit={save} className="grid gap-4 md:grid-cols-2">
      <div><FieldLabel htmlFor="employee-first">First name</FieldLabel><Input id="employee-first" required value={form.firstName} onChange={(event) => field("firstName", event.target.value)} /></div>
      <div><FieldLabel htmlFor="employee-last">Last name</FieldLabel><Input id="employee-last" required value={form.lastName} onChange={(event) => field("lastName", event.target.value)} /></div>
      <div><FieldLabel htmlFor="employee-profile">Portal profile</FieldLabel><select id="employee-profile" value={form.profileId} onChange={(event) => field("profileId", event.target.value)} className="min-h-10 w-full rounded-lg border border-[var(--betanor-border)] bg-white px-3 text-sm"><option value="">Link later</option>{profiles.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div>
      <div><FieldLabel htmlFor="employee-email">Work email</FieldLabel><Input id="employee-email" type="email" value={form.workEmail} onChange={(event) => field("workEmail", event.target.value)} /></div>
      <div><FieldLabel htmlFor="employee-phone">Work phone</FieldLabel><Input id="employee-phone" type="tel" value={form.workPhone} onChange={(event) => field("workPhone", event.target.value)} /></div>
      <div><FieldLabel htmlFor="employee-start">Start date</FieldLabel><Input id="employee-start" required type="date" value={form.hireDate} onChange={(event) => field("hireDate", event.target.value)} /></div>
      <div><FieldLabel htmlFor="employee-probation">Probation end date</FieldLabel><Input id="employee-probation" type="date" value={form.probationEndDate} onChange={(event) => field("probationEndDate", event.target.value)} /></div>
      <div><FieldLabel htmlFor="employee-department">Department</FieldLabel><select id="employee-department" value={form.departmentId} onChange={(event) => field("departmentId", event.target.value)} className="min-h-10 w-full rounded-lg border border-[var(--betanor-border)] bg-white px-3 text-sm"><option value="">Select department</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div>
      <div><FieldLabel htmlFor="employee-position">Position</FieldLabel><select id="employee-position" value={form.positionId} onChange={(event) => field("positionId", event.target.value)} className="min-h-10 w-full rounded-lg border border-[var(--betanor-border)] bg-white px-3 text-sm"><option value="">Select position</option>{positions.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div>
      <div><FieldLabel htmlFor="employee-manager">Immediate manager</FieldLabel><select id="employee-manager" value={form.managerId} onChange={(event) => field("managerId", event.target.value)} className="min-h-10 w-full rounded-lg border border-[var(--betanor-border)] bg-white px-3 text-sm"><option value="">No manager recorded</option>{managers.filter((item) => item.id !== editingId).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div>
      <div><FieldLabel htmlFor="employee-type">Employment type</FieldLabel><select id="employee-type" value={form.employmentType} onChange={(event) => field("employmentType", event.target.value)} className="min-h-10 w-full rounded-lg border border-[var(--betanor-border)] bg-white px-3 text-sm"><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option></select></div>
      <div><FieldLabel htmlFor="employee-salary">Monthly salary (ETB)</FieldLabel><Input id="employee-salary" min="0" step="0.01" type="number" value={form.salary} onChange={(event) => field("salary", event.target.value)} /></div>
      <div><FieldLabel htmlFor="employee-contract">Contract title</FieldLabel><Input id="employee-contract" value={form.contractTitle} onChange={(event) => field("contractTitle", event.target.value)} /></div>
      <div><FieldLabel htmlFor="employee-status">Employment status</FieldLabel><select id="employee-status" value={form.employmentStatus} onChange={(event) => field("employmentStatus", event.target.value)} className="min-h-10 w-full rounded-lg border border-[var(--betanor-border)] bg-white px-3 text-sm"><option value="active">Active</option><option value="on_leave">On leave</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></div>
      <div className="md:col-span-2 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--betanor-border)] pt-4"><span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-900">Standard schedule: Monday–Friday · 8 hours/day · 40 hours/week</span><div className="flex gap-2"><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving…" : editingId ? "Save changes" : "Create employee"}</Button></div></div>
    </form></Modal> : null}
    <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{employees.map((employee) => <Card key={employee.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[var(--betanor-navy)]">{employee.first_name} {employee.last_name}</p><p className="mt-1 text-xs text-[var(--betanor-muted)]">{employee.contract_title || "Employee"} · {employee.employment_status}</p></div><div className="flex gap-1"><Button variant="ghost" size="sm" onClick={() => startEdit(employee)}>Edit</Button><Button variant="ghost" size="sm" onClick={() => void remove(employee)}>Delete</Button></div></div><p className="mt-2 text-xs text-[var(--betanor-muted)]">{employee.work_email || "No work email"}</p></Card>)}</div>
  </>;
}
