import { revalidatePath } from "next/cache";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/server";
export const dynamic = "force-dynamic";
async function createContract(data: FormData) { "use server"; const workspaceId=String(data.get("workspaceId")??""), title=String(data.get("title")??"").trim(); if(!workspaceId||!title)return; const supabase=await createClient(); await supabase.from("contracts").insert({workspace_id:workspaceId,contract_number:`BTNR-CTR-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,5).toUpperCase()}`,title,customer_id:String(data.get("customerId")??"")||null,quotation_id:String(data.get("quotationId")??"")||null,starts_on:String(data.get("startsOn")??"")||null,ends_on:String(data.get("endsOn")??"")||null,value_amount:Number(data.get("value")??0)||null,currency_code:"ETB",place_of_execution:String(data.get("place")??"")||"Addis Ababa, Ethiopia",status:"draft"}); revalidatePath("/workspace/contracts"); }
export default async function ContractsPage(){const supabase=await createClient();const [workspaces,customers,quotes,contracts]=await Promise.all([supabase.from("workspaces").select("id").limit(1),supabase.from("customers").select("id,name"),supabase.from("quotations").select("id,title").eq("status","approved"),supabase.from("contracts").select("id,contract_number,title,status,starts_on,ends_on,value_amount,currency_code,customers(name)").order("created_at",{ascending:false})]);const workspace=workspaces.data?.[0];return <main className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><p className="text-sm font-semibold tracking-[.14em] text-[var(--betanor-blue)] uppercase">Contracts</p><h1 className="mt-3 text-3xl font-semibold text-[var(--betanor-navy)]">Ethiopian commercial agreements.</h1>{workspace?<><Card className="mt-8 p-6"><form action={createContract} className="grid gap-4 md:grid-cols-2"><input type="hidden" name="workspaceId" value={workspace.id}/><Input name="title" required placeholder="Contract title"/><select name="customerId" className="min-h-10 rounded-lg border border-[var(--betanor-border)] px-3 text-sm"><option value="">Customer</option>{customers.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="quotationId" className="min-h-10 rounded-lg border border-[var(--betanor-border)] px-3 text-sm"><option value="">Approved quotation</option>{quotes.data?.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><Input name="value" type="number" min="0" placeholder="Contract value (ETB)"/><Input name="startsOn" type="date"/><Input name="endsOn" type="date"/><Input name="place" defaultValue="Addis Ababa, Ethiopia"/><div className="md:col-span-2"><Button type="submit">Create contract draft</Button></div></form></Card><div className="mt-8 grid gap-4 md:grid-cols-2">{contracts.data?.map(c=><Card key={c.id} className="p-5"><div className="flex justify-between"><div><p className="font-semibold text-[var(--betanor-navy)]">{c.title}</p><p className="text-xs text-[var(--betanor-muted)]">{c.contract_number}</p></div><Badge tone="draft">{c.status}</Badge></div><p className="mt-4 text-sm text-[var(--betanor-muted)]">{c.customers?.[0]?.name||"Customer pending"} · {c.value_amount?`${c.currency_code} ${c.value_amount}`:"Value pending"}</p></Card>)}</div></>:<Card className="mt-8 p-6">Contract access is required.</Card>}</main>}
