import { NextResponse } from "next/server";

import { audit, cleanText, letterAuth } from "@/lib/letters/server";
import { sanitizeLetterHtml } from "@/lib/letters/sanitize";
import { LETTER_CATEGORIES } from "@/lib/letters/types";

export const dynamic = "force-dynamic";
const TEMPLATE_COLUMNS = "id,workspace_id,name,category,subject_template,salutation_template,body_template,closing_template,signatory,signatory_title,allowed_placeholders,is_active,created_by,updated_by,created_at,updated_at";
const SAFE_PLACEHOLDERS = new Set(["recipient_name", "recipient_organization", "reference_number", "letter_date", "customer_name", "employee_name", "tender_reference", "project_name", "quotation_number", "contract_number"]);
function fail(message: string, status = 400) { return NextResponse.json({ error: message }, { status }); }
function placeholders(value: unknown) { return [...new Set((String(value ?? "").match(/\{\{\s*([a-z_]+)\s*\}\}/gi) ?? []).map((item) => item.replace(/[{}\s]/g, "").toLowerCase()))]; }
function templatePayload(body: Record<string, unknown>) {
  const bodyTemplate = sanitizeLetterHtml(body.bodyTemplate); const all = [body.name, body.subjectTemplate, body.salutationTemplate, bodyTemplate, body.closingTemplate, body.signatory, body.signatoryTitle].flatMap(placeholders); if (all.some((value) => !SAFE_PLACEHOLDERS.has(value))) return null;
  const category = cleanText(body.category) || "General Letter"; return { name: cleanText(body.name), category: LETTER_CATEGORIES.includes(category as (typeof LETTER_CATEGORIES)[number]) ? category : "Other", subject_template: cleanText(body.subjectTemplate) || null, salutation_template: cleanText(body.salutationTemplate) || null, body_template: bodyTemplate || "<p></p>", closing_template: cleanText(body.closingTemplate) || null, signatory: cleanText(body.signatory) || null, signatory_title: cleanText(body.signatoryTitle) || null, allowed_placeholders: [...new Set(all)] };
}

export async function GET() { const { supabase, access } = await letterAuth(); if (!access.workspaceId || (!access.permissions.has("letters.read") && !access.permissions.has("letters.manage_templates"))) return fail("Template access is required.", 403); const { data, error } = await supabase.from("letter_templates").select(TEMPLATE_COLUMNS).eq("workspace_id", access.workspaceId).order("name"); if (error) return fail(error.message); return NextResponse.json({ templates: data ?? [] }); }

export async function POST(request: Request) { const { supabase, access } = await letterAuth(); if (!access.workspaceId || !access.userId || !access.permissions.has("letters.manage_templates")) return fail("Template management permission is required.", 403); const payload = templatePayload(await request.json().catch(() => ({}))); if (!payload || payload.name.length < 2 || payload.name.length > 100) return fail("Template name and safe placeholders are required.", 422); const { data, error } = await supabase.from("letter_templates").insert({ ...payload, workspace_id: access.workspaceId, created_by: access.userId, updated_by: access.userId }).select(TEMPLATE_COLUMNS).single(); if (error) return fail(error.message, error.code === "23505" ? 409 : 400); await audit(supabase, access.workspaceId, data.id, "letter.template_created", { name: data.name }); return NextResponse.json({ template: data }, { status: 201 }); }

export async function PATCH(request: Request) { const { supabase, access } = await letterAuth(); if (!access.workspaceId || !access.userId || !access.permissions.has("letters.manage_templates")) return fail("Template management permission is required.", 403); const body = await request.json().catch(() => ({})); const id = cleanText(body.id); if (!id) return fail("A template is required.", 422); const payload = templatePayload(body); if (!payload || payload.name.length < 2) return fail("Template name and safe placeholders are required.", 422); const { data, error } = await supabase.from("letter_templates").update({ ...payload, updated_by: access.userId, updated_at: new Date().toISOString() }).eq("id", id).eq("workspace_id", access.workspaceId).select(TEMPLATE_COLUMNS).maybeSingle(); if (error) return fail(error.message, error.code === "23505" ? 409 : 400); if (!data) return fail("Template not found.", 404); await audit(supabase, access.workspaceId, id, "letter.template_updated", { name: data.name }); return NextResponse.json({ template: data }); }

export async function DELETE(request: Request) { const { supabase, access } = await letterAuth(); if (!access.workspaceId || !access.permissions.has("letters.manage_templates")) return fail("Template management permission is required.", 403); const body = await request.json().catch(() => ({})); const id = cleanText(body.id); if (!id) return fail("A template is required.", 422); const { error } = await supabase.from("letter_templates").delete().eq("id", id).eq("workspace_id", access.workspaceId); if (error) return fail(error.message); await audit(supabase, access.workspaceId, id, "letter.template_deleted", {}); return NextResponse.json({ deleted: true }); }
