import Link from "next/link";

import { BetanorMark } from "@/components/brand/betanor-mark";
import { getPublicContent } from "@/lib/site-content";
import { createClient } from "@/lib/supabase/server";

export async function SiteFooter({ showRfq = false }: { showRfq?: boolean }) {
  const contact = (await getPublicContent(await createClient(), "footer")).get("contact");
  const address = contact?.title || "Eltek Building 103, Bole Woreda 3";
  const contactLine = contact?.body || "+251 98 201 0088 · +251 91 791 1604 · info@betanor.et";
  const [phoneOne, phoneTwo, email] = contactLine.split("·").map((value) => value.trim());
  return <footer className="bg-[var(--betanor-footer-bg)] text-[var(--betanor-footer-text)]"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div className="sm:col-span-2 lg:col-span-1"><BetanorMark className="flex items-center gap-3" dark /><p className="mt-5 max-w-xs text-sm leading-6 text-[var(--betanor-footer-text)]/70">One technology partner for practical, reliable technology environments.</p></div><div><p className="text-sm font-semibold text-[var(--betanor-footer-text)]">Explore</p><div className="mt-4 grid gap-3 text-sm"><Link className="transition-colors hover:text-[var(--betanor-gold)]" href="/about">Company</Link><Link className="transition-colors hover:text-[var(--betanor-gold)]" href="/services">Services & catalogue</Link><Link className="transition-colors hover:text-[var(--betanor-gold)]" href="/projects">Solutions</Link><Link className="transition-colors hover:text-[var(--betanor-gold)]" href="/partner">Partner with us</Link></div></div><div><p className="text-sm font-semibold text-[var(--betanor-footer-text)]">Connect</p><div className="mt-4 grid gap-3 text-sm"><Link className="transition-colors hover:text-[var(--betanor-gold)]" href="/contact">Contact us</Link><Link className="transition-colors hover:text-[var(--betanor-gold)]" href="/careers">Careers</Link><Link className="transition-colors hover:text-[var(--betanor-gold)]" href="/login">Sign in / Sign up</Link>{showRfq ? <Link className="font-semibold text-[var(--betanor-footer-text)] hover:text-[var(--betanor-gold)]" href="/rfq">Request a quotation</Link> : null}</div></div><div><p className="text-sm font-semibold text-[var(--betanor-footer-text)]">Contact</p><address className="mt-4 not-italic text-sm leading-7 text-[var(--betanor-footer-text)]/70">{address}<br />Addis Ababa, Ethiopia<br /><a className="hover:text-[var(--betanor-gold)]" href={`tel:${phoneOne?.replace(/\s/g, "")}`}>{phoneOne}</a>{phoneTwo ? <><br /><a className="hover:text-[var(--betanor-gold)]" href={`tel:${phoneTwo.replace(/\s/g, "")}`}>{phoneTwo}</a></> : null}{email ? <><br /><a className="hover:text-[var(--betanor-gold)]" href={`mailto:${email}`}>{email}</a></> : null}</address></div></div><div className="border-t border-[var(--betanor-footer-text)]/15 px-6 py-5 text-center text-xs text-[var(--betanor-footer-text)]/55">© {new Date().getFullYear()} Betanor General Trading P.L.C. Always Welcome, Always Ready.</div></footer>;
}
