"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

import { Button } from "@/components/ui/button";

export function LetterActions({ id, status, canPublish, canSubmit, canEdit, canDuplicate, canArchive }: { id: string; status: string; canPublish: boolean; canSubmit: boolean; canEdit: boolean; canDuplicate: boolean; canArchive: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  async function action(name: string, endpoint: string, init?: RequestInit) { setBusy(name); setError(""); try { const response = await fetch(endpoint, { method: "POST", ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "The action could not be completed."); if (result.letter?.id && name === "duplicate") router.push(`/workspace/letters/${result.letter.id}`); else if (result.letter?.id && name === "related") router.push(`/workspace/letters/${result.letter.id}`); else router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "The action could not be completed."); } finally { setBusy(""); } }
  const submit = () => { if (window.confirm("Once submitted, this official letter will be finalized and cannot be edited.")) void action("submit", `/api/letters/${id}/submit`); };
  return <div className="flex flex-wrap items-center gap-2">{canEdit ? <Button variant="outline" size="sm" onClick={() => router.push(`/workspace/letters/${id}/edit`)}>Edit</Button> : null}{status === "DRAFT" && canPublish ? <Button size="sm" onClick={() => void action("publish", `/api/letters/${id}/publish`)} disabled={Boolean(busy)}>{busy === "publish" ? "Publishing…" : "Publish"}</Button> : null}{status === "PUBLISHED" && canSubmit ? <Button size="sm" variant="secondary" onClick={submit} disabled={Boolean(busy)}>{busy === "submit" ? "Finalizing…" : "Submit & finalize"}</Button> : null}{canDuplicate ? <Button variant="outline" size="sm" onClick={() => void action("duplicate", `/api/letters/${id}/duplicate`)} disabled={Boolean(busy)}>{busy === "duplicate" ? "Duplicating…" : "Duplicate draft"}</Button> : null}{canDuplicate ? <Button variant="outline" size="sm" onClick={() => void action("related", `/api/letters/${id}/related`, { body: JSON.stringify({ relatedType: "follow_up_to" }) })} disabled={Boolean(busy)}>Follow-up letter</Button> : null}{canArchive && status !== "SUBMITTED" ? <Button variant="ghost" size="sm" onClick={() => void action("archive", `/api/letters/${id}/archive`)} disabled={Boolean(busy)}>Archive</Button> : null}{error ? <span role="alert" className="basis-full text-xs text-[var(--betanor-danger)]">{error}</span> : null}</div>;
}
