import Link from "next/link";

import { ContentCard, ContentGrid } from "@/components/public/content-grid";
import { PublicHeader } from "@/components/navigation/public-header";
import { SiteFooter } from "@/components/navigation/site-footer";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const services = ["Digital solutions consulting", "Software development & implementation", "IT infrastructure & data center", "Managed IT support", "Security & surveillance", "Training & capacity building"];

export default function Home() {
  return <><PublicHeader /><main>
    <section className="relative isolate overflow-hidden bg-[var(--betanor-dark-navy)] px-6 py-20 text-white lg:px-8 lg:py-30"><div className="absolute inset-0 opacity-35 [background-image:linear-gradient(rgba(255,255,255,.09)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.09)_1px,transparent_1px)] [background-size:52px_52px]"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.12fr_0.88fr]"><div><p className="text-sm font-semibold tracking-[0.14em] text-[var(--betanor-light-gold)] uppercase">Betanor General Trading P.L.C.</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold tracking-tight sm:text-6xl lg:text-7xl">Technology You Can Rely On.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">A dependable technology partner for consulting, software, IT infrastructure, products, security, implementation, training, and long-term support.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/projects"><Button size="lg">Explore solutions</Button></Link><Link href="/contact"><Button size="lg" variant="outline" className="border-white/35 bg-transparent text-white hover:bg-white/10 hover:text-white">Request consultation</Button></Link></div><p className="mt-8 text-sm font-medium text-slate-400">Always Welcome, Always Ready.</p></div><div className="relative mx-auto aspect-square w-full max-w-110 rounded-[2rem] border border-white/15 bg-gradient-to-br from-[#174a91] via-[var(--betanor-navy)] to-[#081c3b] p-8 shadow-2xl"><div className="absolute inset-8 rounded-[1.5rem] border border-white/10"/><div className="absolute top-14 right-12 size-18 rounded-2xl bg-[var(--betanor-gold)]/25 blur-sm"/><div className="absolute bottom-13 left-12 size-28 rounded-full border border-[var(--betanor-light-gold)]/55"/><div className="absolute inset-0 grid place-items-center"><div className="grid size-40 place-items-center rounded-full border border-white/20 bg-white/8 text-center backdrop-blur-sm"><span className="text-sm font-semibold tracking-[0.14em] text-[var(--betanor-light-gold)] uppercase">Consult<br />Implement<br />Support</span></div></div></div></div></section>
    <section className="bg-white"><div className="mx-auto max-w-7xl px-6 py-14 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold tracking-[0.14em] text-[var(--betanor-blue)] uppercase">What we do</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-[var(--betanor-navy)]">Solutions that connect strategy to reliable operations.</h2></div><Link className="text-sm font-semibold text-[var(--betanor-blue)]" href="/services">View all services →</Link></div></div><ContentGrid>{services.map((service) => <ContentCard key={service} title={service}>Focused expertise from discovery and architecture through implementation, support, and measurable improvement.</ContentCard>)}</ContentGrid></section>
    <section className="bg-[var(--betanor-surface)] px-6 py-14 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 rounded-2xl bg-white p-8 shadow-[var(--betanor-shadow-card)] lg:grid-cols-[1fr_auto] lg:items-center"><div><Badge tone="draft">Start a conversation</Badge><h2 className="mt-4 text-3xl font-semibold tracking-tight text-[var(--betanor-navy)]">Planning a technology project?</h2><p className="mt-3 max-w-2xl leading-7 text-[var(--betanor-muted)]">Share your organization, priorities, and timeline with our team. We will help frame the right next step.</p></div><Link href="mailto:info@betanor.et?subject=Quotation%20request"><Button size="lg">Request a quote</Button></Link></div></section>
  </main><SiteFooter /></>;
}
