"use client";

import { useState } from "react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Slip = { id: string; employee_id: string; gross_pay: number; deductions: number; net_pay: number; currency_code: string; employees?: { first_name?: string; last_name?: string; employee_number?: string }[] };

export function PayrollSpreadsheet({ cycleId, editable, slips }: { cycleId: string; editable: boolean; slips: Slip[] }) {
  const [rows, setRows] = useState(slips.map((slip) => ({ ...slip, gross_pay: Number(slip.gross_pay ?? 0), deductions: Number(slip.deductions ?? 0) })));
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  function setValue(id: string, field: "gross_pay" | "deductions", value: string) { setRows((current) => current.map((row) => row.id === id ? { ...row, [field]: Number(value) || 0, net_pay: field === "gross_pay" ? (Number(value) || 0) - row.deductions : row.gross_pay - (Number(value) || 0) } : row)); }
  async function save() { setSaving(true); setMessage(""); const response = await fetch(`/api/payroll/cycles/${cycleId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ payslips: rows.map((row) => ({ id: row.id, grossPay: row.gross_pay, deductions: row.deductions })) }) }); const payload = await response.json().catch(() => ({})); setSaving(false); setMessage(response.ok ? "Payroll values saved." : payload.error || "Could not save payroll."); }
  return <div className="mt-4"><div className="overflow-x-auto rounded-lg border border-[var(--betanor-border)]"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-slate-50 text-[var(--betanor-muted)]"><tr><th className="px-3 py-2">Employee</th><th className="px-3 py-2">Employee ID</th><th className="px-3 py-2">Gross</th><th className="px-3 py-2">Deductions</th><th className="px-3 py-2">Net</th><th className="px-3 py-2">Currency</th></tr></thead><tbody className="divide-y divide-[var(--betanor-border)]">{rows.map((row) => <tr key={row.id}><td className="px-3 py-2 font-semibold text-[var(--betanor-navy)]">{row.employees?.[0]?.first_name} {row.employees?.[0]?.last_name}</td><td className="px-3 py-2">{row.employees?.[0]?.employee_number || "—"}</td><td className="px-3 py-2">{editable ? <Input className="h-8 min-h-8 w-28 text-xs" type="number" min="0" step="0.01" value={row.gross_pay} onChange={(event) => setValue(row.id, "gross_pay", event.target.value)} /> : row.gross_pay.toFixed(2)}</td><td className="px-3 py-2">{editable ? <Input className="h-8 min-h-8 w-28 text-xs" type="number" min="0" step="0.01" value={row.deductions} onChange={(event) => setValue(row.id, "deductions", event.target.value)} /> : row.deductions.toFixed(2)}</td><td className="px-3 py-2 font-semibold">{Math.max(0, row.net_pay).toFixed(2)}</td><td className="px-3 py-2">{row.currency_code}</td></tr>)}</tbody></table></div><div className="mt-3 flex flex-wrap items-center gap-2">{editable ? <Button size="sm" onClick={save} disabled={saving}>{saving ? "Saving…" : "Save payroll"}</Button> : null}<a className="rounded-lg border border-[var(--betanor-field-border)] px-3 py-2 text-xs font-semibold text-[var(--betanor-navy)] hover:bg-slate-50" href={`/api/payroll/cycles/${cycleId}/export/xls`}>Excel</a><a className="rounded-lg border border-[var(--betanor-field-border)] px-3 py-2 text-xs font-semibold text-[var(--betanor-navy)] hover:bg-slate-50" href={`/api/payroll/cycles/${cycleId}/export/doc`}>Word</a><a className="rounded-lg border border-[var(--betanor-field-border)] px-3 py-2 text-xs font-semibold text-[var(--betanor-navy)] hover:bg-slate-50" href={`/api/payroll/cycles/${cycleId}/export/pdf`}>PDF</a>{message ? <span className="text-xs text-[var(--betanor-muted)]">{message}</span> : null}</div></div>;
}
