import { revalidatePath } from "next/cache";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
async function createProject(data: FormData) { "use server"; const workspaceId = String(data.get("workspaceId") ?? ""), name = String(data.get("name") ?? "").trim(); if (!workspaceId || !name) return; const supabase = await createClient(); await supabase.from("projects").insert({ workspace_id: workspaceId, project_code: `BTNR-PRJ-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,5).toUpperCase()}`, name, customer_id: String(data.get("customerId") ?? "") || null, contract_id: String(data.get("contractId") ?? "") || null, description: String(data.get("description") ?? "").trim() || null, starts_on: String(data.get("startsOn") ?? "") || null, ends_on: String(data.get("endsOn") ?? "") || null, budget_amount: Number(data.get("budget") ?? 0) || null, currency_code: "ETB" }); revalidatePath("/workspace/projects"); }
export default async function ProjectsPage() { const supabase = await createClient(); const [workspaces, customers, contracts, projects] = await Promise.all([supabase.from("workspaces").select("id").limit(1),supabase.from("customers").select("id,name").order("name"),supabase.from("contracts").select("id,title").order("created_at",{ascending:false}),supabase.from("projects").select("id,project_code,name,status,starts_on,ends_on,budget_amount,customers(name),contracts(title)").order("created_at",{ascending:false})]); const workspace=workspaces.data?.[0]; return <main className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><p className="text-sm font-semibold tracking-[0.14em] text-[var(--betanor-blue)] uppercase">Projects</p><h1 className="mt-3 text-3xl font-semibold text-[var(--betanor-navy)]">Deliver from contract to outcome.</h1>{workspace ? <><Card className="mt-8 p-6"><form action={createProject} className="grid gap-4 md:grid-cols-2"><input name="workspaceId" type="hidden" value={workspace.id}/><Input name="name" required placeholder="Project name"/><select name="customerId" className="min-h-10 rounded-lg border border-[var(--betanor-border)] px-3 text-sm"><option value="">Customer</option>{customers.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="contractId" className="min-h-10 rounded-lg border border-[var(--betanor-border)] px-3 text-sm"><option value="">Linked contract</option>{contracts.data?.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><Input name="budget" min="0" type="number" placeholder="Budget (ETB)"/><Input name="startsOn" type="date"/><Input name="endsOn" type="date"/><textarea name="description" className="rounded-lg border border-[var(--betanor-border)] px-3 py-2 text-sm" placeholder="Scope and delivery notes"/><div className="md:col-span-2"><Button type="submit">Create project</Button></div></form></Card><div className="mt-8 grid gap-4 md:grid-cols-2">{projects.data?.map(project=><Card key={project.id} className="p-5"><div className="flex justify-between gap-3"><div><p className="font-semibold text-[var(--betanor-navy)]">{project.name}</p><p className="mt-1 text-xs text-[var(--betanor-muted)]">{project.project_code}</p></div><Badge tone="draft">{project.status}</Badge></div><p className="mt-4 text-sm text-[var(--betanor-muted)]">{project.customers?.[0]?.name || "Internal project"} · {project.budget_amount ? `ETB ${project.budget_amount}` : "Budget to be confirmed"}</p></Card>)}</div></> : <Card className="mt-8 p-6">Project access is required.</Card>}</main>; }
