import { notFound, redirect } from "next/navigation";

import { LetterForm } from "@/components/letters/letter-form";
import { getLetter } from "@/lib/letters/server";
import { createClient } from "@/lib/supabase/server";
import { resolveWorkspace } from "@/lib/workspace-context";

export const dynamic = "force-dynamic";

export default async function EditLetterPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const access = await resolveWorkspace(supabase); if (!access.workspaceId) redirect("/workspace/letters"); const { letter } = await getLetter(supabase, access.workspaceId, id); if (!letter) notFound(); if (letter.status === "SUBMITTED") redirect(`/workspace/letters/${id}`); const canEdit = access.permissions.has("letters.edit_all") || (access.permissions.has("letters.edit_own") && letter.prepared_by === access.userId); if (!canEdit) redirect(`/workspace/letters/${id}`);
  const [{ data: departments }, { data: customers }, { data: employees }, { data: projects }, { data: contracts }, { data: quotations }, { data: rfqs }] = await Promise.all([
    supabase.from("departments").select("id,name,code").eq("workspace_id", access.workspaceId).eq("status", "active").order("name"), supabase.from("customers").select("id,name,legal_name").eq("workspace_id", access.workspaceId).order("name").limit(200), supabase.from("employees").select("id,profile_id,first_name,last_name,employee_number").eq("workspace_id", access.workspaceId).eq("employment_status", "active").order("first_name").limit(200), supabase.from("projects").select("id,name,project_code").eq("workspace_id", access.workspaceId).order("name").limit(200), supabase.from("contracts").select("id,title,contract_number").eq("workspace_id", access.workspaceId).order("title").limit(200), supabase.from("quotations").select("id,title,quotation_number").eq("workspace_id", access.workspaceId).order("title").limit(200), supabase.from("rfq_requests").select("id,reference,organization").eq("workspace_id", access.workspaceId).order("created_at", { ascending: false }).limit(200),
  ]);
  return <main className="mx-auto max-w-5xl px-5 py-8 sm:px-6 lg:px-8 lg:py-10"><div className="mb-8"><p className="text-sm font-semibold tracking-[0.14em] text-[var(--betanor-blue)] uppercase">Documents · Letters</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-[var(--betanor-navy)]">Edit {letter.reference_number}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--betanor-muted)]">Draft and published letters remain governed records. Submission permanently locks the official content.</p></div><LetterForm letter={letter} departments={(departments ?? []).map((item) => ({ id: item.id, label: `${item.name} · ${item.code}` }))} customers={(customers ?? []).map((item) => ({ id: item.id, label: item.legal_name || item.name }))} employees={(employees ?? []).map((item) => ({ id: item.id, label: `${item.first_name} ${item.last_name} · ${item.employee_number}` }))} approvers={(employees ?? []).filter((item) => item.profile_id).map((item) => ({ id: item.profile_id as string, label: `${item.first_name} ${item.last_name} · ${item.employee_number}` }))} projects={(projects ?? []).map((item) => ({ id: item.id, label: `${item.name} · ${item.project_code}` }))} contracts={(contracts ?? []).map((item) => ({ id: item.id, label: `${item.title} · ${item.contract_number}` }))} quotations={(quotations ?? []).map((item) => ({ id: item.id, label: `${item.title} · ${item.quotation_number}` }))} rfqs={(rfqs ?? []).map((item) => ({ id: item.id, label: `${item.reference} · ${item.organization}` }))} canEditDate={access.permissions.has("letters.edit_all")} /></main>;
}
